name: CI
on: [push]

env:
  TEST_TAG: qwofin/lib-nimic:test

jobs:
  build-test-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and export Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          target: builder
          push: false
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Lint
        run: |
          docker run --rm ${{ env.TEST_TAG }} npm run lint
      - name: Test
        env:
          DOWNLOAD_DIR: /tmp
          COMPLETED_DIR: /tmp
        run: |
          docker run --rm \
          -e DOWNLOAD_DIR \
          -e COMPLETED_DIR \
          ${{ env.TEST_TAG }} npm run test:faked
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          target: release
          push: true
          tags: |
            ghcr.io/qwofin/lib-nimic:latest
